### ISSUE TITLE
GSI Lag and deltat(nodays)

### ISSUE THREAD

**Issue by AliKhalid3110** [GCEL/DALEC-Grass#1]
hi, 

Can you kindly elaborate on what is stored in deltat(nodays) with an example and how it is used to calculate GSI Lag? kindly also, elaborate on what is GSI lag and the purpose of tmp_x and tmp_m arrays.

It will be really helpful if you can also elaborate on the following variables:
fol_turn_crit=pars(24)-1d0
lab_turn_crit=pars(3)-1d0

Thank You.

**Comment by vmyrgiotis** [comment]
Hi. 
> The deltat is an array of the size of the simulation time-step e.g. if the model is run on daily time step for e.g 365 days the deltat is an array with length = 365 and every element of the array is = 1.
> tmp_x , tmp_m : these  are arrays used to ensure the correct GSI value is calculated and added to flux#18  regardless of the simulation time step e.g. daily, weekly, monthly 
> fol_turn_crit , lab_turn_crit : just the names given to the parameters #3 and #24 that, in turn, are used to calibrate how the GSI-based plant growth curve and NPP carbon allocation to leaves, stems and roots are linked

PS. apologies for replying to these questions with such a long delay but this repository is not actively monitored.
